/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Exemplo8;

import javax.swing.JOptionPane;

/**
 *
 * @author Geral
 */
public class Exempo8_4 extends javax.swing.JFrame {

    /**
     * Creates new form Exempo8_4
     */
    public Exempo8_4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxIngles = new javax.swing.JCheckBox();
        jCheckBoxInformatica = new javax.swing.JCheckBox();
        jBTvericar = new javax.swing.JButton();
        jButton2marcar = new javax.swing.JButton();
        jButton3desmarcar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Exemplo8.4");

        jCheckBoxIngles.setText("Java SE");
        jCheckBoxIngles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxInglesActionPerformed(evt);
            }
        });

        jCheckBoxInformatica.setText("PHP");

        jBTvericar.setMnemonic('v');
        jBTvericar.setText("Verificar");
        jBTvericar.setToolTipText("Verifica o formulario");
        jBTvericar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTvericarActionPerformed(evt);
            }
        });

        jButton2marcar.setMnemonic('M');
        jButton2marcar.setText("Marcar");
        jButton2marcar.setToolTipText("Marca as no formulario");
        jButton2marcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2marcarActionPerformed(evt);
            }
        });

        jButton3desmarcar.setMnemonic('D');
        jButton3desmarcar.setText("Desmarcar");
        jButton3desmarcar.setToolTipText("Desmarca o formulario");
        jButton3desmarcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3desmarcarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3desmarcar)
                    .addComponent(jButton2marcar)
                    .addComponent(jBTvericar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jCheckBoxInformatica, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCheckBoxIngles, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jCheckBoxIngles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxInformatica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jBTvericar)
                .addGap(18, 18, 18)
                .addComponent(jButton2marcar)
                .addGap(18, 18, 18)
                .addComponent(jButton3desmarcar)
                .addGap(77, 77, 77))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3desmarcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3desmarcarActionPerformed
        // TODO add your handling code here:
        jCheckBoxInformatica.setSelected(false);
        jCheckBoxIngles.setSelected(false);
    }//GEN-LAST:event_jButton3desmarcarActionPerformed

    private void jButton2marcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2marcarActionPerformed
        // TODO add your handling code here:
        jCheckBoxInformatica.setSelected(true);
        jCheckBoxIngles.setSelected(true);
    }//GEN-LAST:event_jButton2marcarActionPerformed

    private void jBTvericarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTvericarActionPerformed
        // TODO add your handling code here:
        String selecao = "Selecionados: ";
        if(jCheckBoxIngles.isSelected()){
            selecao += "\n"+jCheckBoxIngles.getText();
        }
        if(jCheckBoxInformatica.isSelected()){
            selecao += "\n"+jCheckBoxInformatica.getText();
        }
        
        
        if(!jCheckBoxIngles.isSelected() && !jCheckBoxInformatica.isSelected()){
            JOptionPane.showMessageDialog(null, "Nenhum Curso selecionado");
        }else{
            JOptionPane.showMessageDialog(null, selecao);
        }
        
    }//GEN-LAST:event_jBTvericarActionPerformed

    private void jCheckBoxInglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxInglesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxInglesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exempo8_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exempo8_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exempo8_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exempo8_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exempo8_4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBTvericar;
    private javax.swing.JButton jButton2marcar;
    private javax.swing.JButton jButton3desmarcar;
    private javax.swing.JCheckBox jCheckBoxInformatica;
    private javax.swing.JCheckBox jCheckBoxIngles;
    // End of variables declaration//GEN-END:variables
}
